swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Dreamkast"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
  - name: "speaker"
    description: "Operations about user"
    externalDocs:
      description: "Find out more about our store"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /{event_name}/speakers:
    post:
      tags:
        - "speaker"
      summary: "Create user"
      produces:
        - "application/json"
      responses:
        default:
          description: "successful operation"
    get:
      tags:
        - "speaker"
      summary: "Get users"
      produces:
        - "application/json"
      responses:
        default:
          description: "successful operation"
  /{event_name}/speakers/{id}:
    get:
      tags:
        - "speaker"
      summary: "Get user"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Profile"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
    put:
      tags:
        - "speaker"
      summary: "Update user"
      produces:
        - "application/json"
      responses:
        default:
          description: "successful operation"
    delete:
      tags:
        - "speaker"
      summary: "Delete user"
      produces:
        - "application/json"
      responses:
        default:
          description: "successful operation"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Profile:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"
      sub:
        type: "string"
      industry_id:
        type: "integer"
      occupation:
        type: "string"
      company_name:
        type: "string"
      company_email:
        type: "string"
      company_address:
        type: "string"
      company_tel:
        type: "string"
      department:
        type: "string"
      position:
        type: "string"
    xml:
      name: "Profile"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"